### ISSUE TITLE
به هم ریختن منو در نمایش در موبایل

### ISSUE THREAD

**Issue by alifattahi** [Alizadeh118/vuepress-theme-default-rtl#1]
سلام
ممنون از زحمتی که برای فارسی کردن پروژه کشیدید.
یک اشکل کوچک وجود داره.

در حالت responsive در موبایل
منو های بالا به هم میریزه و میاد پایین. 
در صورتی که لینک زیر را در حالت موبایل نگاه کنید متوجه منظورم میشید

https://alizadeh118.github.io/vuepress-theme-default-rtl/

**Comment by Alizadeh118** [comment]
سلام
ممنون از توجهتون
حتما اصلاحش میکنم
